// The whole drill plan. Edit freely — the app reads from this.
// tags: "KEY" | "MATH" | "FAST" | "BUFFER"
export const PLAN = [
  { n: "P0", name: "Spud in", sessions: [
    { id: "S0", t: "Set up the rig + crack the subscript code", a: "Make one Anki deck. Then DON'T card the nomenclature — learn the subscript grammar instead (o/g/w = phase · i/b/a = state · −bar = average · D = dimensionless · caps = totals). Bookmark the nomenclature photo as a lookup. Symbols get carded later, in context, as concepts.", time: "20m", pp: 3, tags: ["KEY"] },
  ]},
  { n: "P1", name: "Foundations · build the habit", sessions: [
    { id: "S1", t: "Ch 1 — Introduction (1.1–1.4)", a: "Read 6 pp. 5 cards: what reservoir engineering actually is + what the job does.", time: "25m", pp: 6, tags: [] },
    { id: "S2", t: "2.1 Reservoir Geology + 2.2 Origin of Oil", a: "Read, 6 cards.", time: "30m", pp: 9, tags: [] },
    { id: "S3", t: "2.3 Reservoir Rocks + 2.4 Geological Traps", a: "Read, 6 cards. Sketch the trap types from blank.", time: "30m", pp: 8, tags: [] },
    { id: "S4", t: "2.5 Reservoir Fluids + 2.6 Reservoir Pressures", a: "Read, 6 cards incl. pressure gradients.", time: "30m", pp: 5, tags: [] },
    { id: "S5", t: "2.7 Phase Diagram & Types of Reservoir", a: "Draw the P–T envelope and label all 5 reservoir types from blank.", time: "30m", pp: 4, tags: ["KEY"] },
    { id: "S6", t: "2.8 Drive Mechanisms + 2.9 Units/Symbols", a: "Read, one line each for the drive mechanisms.", time: "30m", pp: 9, tags: ["KEY"] },
    { id: "S7", t: "3.1 Porosity", a: "Read, cards, work one porosity calc.", time: "30m", pp: 5, tags: [] },
    { id: "S8", t: "3.2 Compressibility + 3.3 Permeability", a: "Read, work one Darcy-units perm calc.", time: "35m", pp: 8, tags: ["MATH"] },
    { id: "S9", t: "3.4 Capillary Pressure", a: "You've done SCAL — quiz yourself first, read only gaps. Pc curve + Leverett J.", time: "25m", pp: 6, tags: ["FAST"] },
    { id: "S10", t: "3.5 Relative Permeability", a: "Quiz first. Sketch a kr–Sw plot from blank: endpoints, wettability.", time: "25m", pp: 6, tags: ["FAST"] },
    { id: "S11", t: "3.6 Statistical Measures", a: "Read, cards.", time: "25m", pp: 6, tags: [] },
    { id: "C1", t: "Consolidation #1", a: "No new reading. From blank: phase envelope, the drive mechanisms, a kr–Sw curve. Redo the porosity + perm calcs. Then Anki only.", time: "35m", pp: 0, tags: ["BUFFER"] },
  ]},
  { n: "P2", name: "Fluids & flow", sessions: [
    { id: "S12", t: "4.1 Sampling & Measurement Methods", a: "Read, cards.", time: "30m", pp: 4, tags: [] },
    { id: "S13", t: "4.2 Key Properties (Bo, Rs, Bg…)", a: "Read. Define each property from blank.", time: "35m", pp: 5, tags: ["KEY"] },
    { id: "S14", t: "4.3 Properties from Lab Data", a: "Read, work one example end-to-end.", time: "35m", pp: 17, tags: ["MATH"] },
    { id: "S15", t: "4.4 Correlations + 4.5 Gas Properties", a: "Read, work one z-factor / gas FVF.", time: "35m", pp: 7, tags: ["MATH"] },
    { id: "S16", t: "5.1–5.2 Darcy: flow systems + incompressible", a: "You use this in LeCarbonStorage. Derive radial steady-state from memory, read gaps.", time: "30m", pp: 6, tags: ["FAST"] },
    { id: "S17", t: "5.3–5.4 Compressible flow + Darcy & potential", a: "Read gaps, cards.", time: "30m", pp: 10, tags: ["FAST"] },
  ]},
  { n: "P3", name: "Volumetrics & material balance · the core", sessions: [
    { id: "S18", t: "6.1 Definitions & Terms (OOIP, OGIP, RF…)", a: "Read, build a glossary card set.", time: "30m", pp: 9, tags: [] },
    { id: "S19", t: "6.2 Volumetric Method", a: "Work the OOIP volumetric calc end-to-end.", time: "35m", pp: 13, tags: ["KEY", "MATH"] },
    { id: "S20", t: "6.3 Averaging Reservoir Pressure", a: "Read, cards.", time: "25m", pp: 2, tags: [] },
    { id: "S21", t: "6.4 Monte Carlo Simulation", a: "Read — your Vortex/COSTRA stats brain will like this.", time: "30m", pp: 16, tags: [] },
    { id: "S22", t: "7.1 Concept of Volume Balance", a: "Read, cards.", time: "25m", pp: 1, tags: [] },
    { id: "S23", t: "7.2 Derivation of the General MBE", a: "Follow line by line, then rewrite the derivation yourself from blank.", time: "40m", pp: 4, tags: ["KEY", "MATH"] },
    { id: "S24", t: "7.3 Particular Equations", a: "Tabulate which terms drop out for each reservoir type.", time: "35m", pp: 12, tags: [] },
    { id: "S25", t: "7.4 Drive Indexes", a: "Read, work one drive-index calc.", time: "30m", pp: 3, tags: ["MATH"] },
    { id: "S26", t: "7.5 Special Notes + 7.6 Linear Models (Havlena–Odeh)", a: "Read, cards on the straight-line method.", time: "35m", pp: 14, tags: [] },
    { id: "S27", t: "7.7 Fractured Reservoirs + 7.8 Forecasting", a: "Read, cards.", time: "30m", pp: 13, tags: [] },
    { id: "C2", t: "Consolidation #2", a: "Re-derive the general MBE from blank (as far as you get). Redo OOIP volumetric + a drive-index calc. Anki review.", time: "40m", pp: 0, tags: ["BUFFER"] },
  ]},
  { n: "P4", name: "Transient flow & decline · the steep part", sessions: [
    { id: "S28", t: "8.1 Production Decline Properties", a: "Read, cards.", time: "30m", pp: 11, tags: [] },
    { id: "S29", t: "8.2 Analytical Models (Arps)", a: "Work all three: exponential, hyperbolic, harmonic.", time: "35m", pp: 9, tags: ["KEY", "MATH"] },
    { id: "S30", t: "8.3 Empirical Models", a: "Read, cards.", time: "30m", pp: 15, tags: [] },
    { id: "S31", t: "8.4 Type Curves + 8.5 Statistical Models", a: "Read, cards.", time: "30m", pp: 9, tags: [] },
    { id: "S32", t: "9.1 Develop the Diffusivity Equation", a: "Derive it slowly, one assumption at a time. List every assumption.", time: "40m", pp: 11, tags: ["MATH"] },
    { id: "S33", t: "9.2 Analytical Solutions", a: "Follow the line-source solution carefully.", time: "40m", pp: 7, tags: ["MATH"] },
    { id: "S34", t: "9.3 van Everdingen–Hurst Solutions", a: "Nail the dimensionless trio: tD, rD, pD.", time: "35m", pp: 3, tags: ["KEY"] },
    { id: "S35", t: "9.4 Approximate Solutions & Applications", a: "Work the Ei-function / log-approximation example.", time: "35m", pp: 17, tags: ["MATH"] },
    { id: "S36", t: "9.5 Superposition Principle", a: "Work one superposition-in-time example.", time: "35m", pp: 7, tags: ["KEY", "MATH"] },
    { id: "S37", t: "9.6 Well Test Data Analysis", a: "Label a semilog plot from blank: skin, p*.", time: "30m", pp: 19, tags: [] },
    { id: "C3", t: "Consolidation #3 — the gatekeeper", a: "From blank: the diffusivity assumptions, the dimensionless trio, the log-approximation. Don't move on until this feels okay — it pays rent in every well test.", time: "40m", pp: 0, tags: ["BUFFER"] },
  ]},
  { n: "P5", name: "Influx, coning, displacement, segregation", sessions: [
    { id: "S38", t: "10.1 Water Influx — Material Balance Models", a: "Read, cards.", time: "30m", pp: 12, tags: [] },
    { id: "S39", t: "10.2 Steady + 10.3 Unsteady State (vEH aquifer)", a: "Read, work one We calc.", time: "35m", pp: 17, tags: ["MATH"] },
    { id: "S40", t: "10.4 Pseudosteady (Fetkovich) + 10.5 Empirical", a: "Read, cards.", time: "30m", pp: 17, tags: [] },
    { id: "S41", t: "10.6 Performance Forecasting", a: "Read, cards.", time: "25m", pp: 10, tags: [] },
    { id: "S42", t: "11.1 Critical Flow Rate + 11.2 Breakthrough Time", a: "Read, work one critical-rate calc.", time: "30m", pp: 11, tags: ["MATH"] },
    { id: "S43", t: "11.3 Forecasting + 11.4 WOC Stability", a: "Read, cards.", time: "25m", pp: 17, tags: [] },
    { id: "S44", t: "12.1 Two Immiscible Fluids + 12.2 Piston-Like", a: "Read, cards.", time: "30m", pp: 14, tags: [] },
    { id: "S45", t: "12.3 Fractional Flow Equation", a: "Derive fw, sketch fw–Sw. This IS your CO₂ plume.", time: "35m", pp: 4, tags: ["KEY", "MATH"] },
    { id: "S46", t: "12.4 Buckley–Leverett + 12.5 Welge Avg Sat", a: "Work the tangent construction by hand.", time: "40m", pp: 6, tags: ["KEY", "MATH"] },
    { id: "S47", t: "12.6 Forecasting + 12.7 Segregated Flow", a: "Read, cards.", time: "30m", pp: 22, tags: [] },
    { id: "S48", t: "13.1 Segregation without Counter Flow", a: "Read, cards.", time: "30m", pp: 21, tags: [] },
    { id: "S49", t: "13.2 Segregation with Counter Flow", a: "Read, cards.", time: "30m", pp: 9, tags: [] },
    { id: "C4", t: "Consolidation #4 — TD", a: "From blank: fractional flow + B–L tangent, the MBE skeleton, the diffusivity trio. Full Anki sweep. Then write a one-page 'what this book gave me' map.", time: "45m", pp: 0, tags: ["BUFFER"] },
  ]},
]
